{{- if and .Values.config.apiKeySecret.create .Values.config.apiKeySecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.apiKeySecret.secretName }}
  labels:
    {{- include "cost-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.apiKeySecret.secretKey }}: {{ .Values.config.apiKeySecret.value | b64enc }}
{{- end }}

