apiVersion: v2
name: cost-agent
description: A Helm chart for Kubernetes cost monitoring agent
type: application
version: 0.1.0
appVersion: "v1.0.11"
keywords:
  - cost-monitoring
  - kubernetes
  - metrics
maintainers:
  - name: cost-agent-team

